"""
LeetCode undefined: Subsets II
URL: https://leetcode.com/problems/subsets-ii/
Difficulty: Medium
Category: Array, Backtracking, Bit Manipulation

Approach:
This implementation uses a recursive Depth-First Search (DFS) to explore all possible combinations of picking or not picking each number, thereby generating all subsets.

Key Observation:
Sorting the input array `nums` helps in grouping duplicate elements, and using a `set` to store `tuple` representations of subsets automatically handles duplicate subsets generated by the DFS, ensuring only unique subsets are returned.

Complexity:
- Time Complexity: O(N * 2^N) (Sorting takes O(N log N). The DFS explores up to 2^N potential subsets. For each subset, constructing it and converting it to a tuple for set insertion takes O(N), leading to an overall O(N * 2^N) time complexity.)
- Space Complexity: O(N * 2^N) (The `res` set stores up to 2^N unique subsets, each potentially containing N elements, resulting in O(N * 2^N) space. The recursion stack for DFS also consumes O(N) space.)
"""

# --- LEETVAULT CODE START ---
class Solution:
    def subsetsWithDup(self, nums: List[int]) -> List[List[int]]:
        res=set()
        def dfs(ind,l):
            if ind>=len(nums):
                res.add(tuple(l[:]))
                return
            pick=dfs(ind+1,l+[nums[ind]])
            notpick=dfs(ind+1,l)
        nums.sort()
        dfs(0,[])
        res=list(map(list,res))
        return res